name: Auto Fix
on: [push]
jobs:
  auto_fix_by_tomi_setiawan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: pip install autopep8 autoflake isort black
    - name: Check for showstoppers
      run: autopep8 --verbose --in-place --recursive --aggressive --aggressive --ignore=W605. *.py
    - name: Remove unused imports and variables
      run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
    - name: Auto Fix
      run: isort . black .
    - name: Code Analysis
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto Fix'
