name: Auto Fix
on: [push]
jobs:
  auto_fix_by_tomi_setiawan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install black
    - name: Auto Fix
      run: python -m black .
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Auto Fix with Black'

