name: Auto Fix
on: [push]
jobs:
  auto_fix_by_tomi_setiawan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 black isort autoflake
      - name: Check for showstoppers
        run: |
          autopep8 --verbose --in-place --recursive --aggressive --aggressive --ignore=W605. *.py
      - name: Auto Fix
        run: |
          black --exclude=venv .
          isort --skip-glob='**/venv/**' .
      - name: Remove unused imports
        run: |
          autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
      - name: Code Analysis
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto Fix"
